### PR TITLE
Hotfix/detector from nur

### LINKED ISSUE #657: Reading normal Detector from nur file not working
**Describe the issue**
When trying to load a normal Detector (i.e. not a Generic one) from a `nur` file, an error is thrown. The cause is line 389 in NuRadioRecoio.py, where the `__new__` method is called. At some point (I believe this happened in commit 844f3aa9be081da98b62bd593a40da9cfaa52114 , where the concept of GenericDetector was introduced) the `json_filename` parameter in this method changed from an optional to required parameter. So now the call on line 389 is missing a required parameter.

Interestingly, the GenericDetector does not produce this error because its `__new__` method is not overwritten.

**Additional context**
MWE to reproduce the error:
```python
import NuRadioReco.modules.io.eventReader.

reader = NuRadioReco.modules.io.eventReader.eventReader()
reader.begin('path/to/nur', read_detector=True)
detector = reader.get_detector()
```

### PR DESCRIPTION
**Pull request by fschlueter**
Fixes #657.

### CODE REVIEW

**Review by sjoerd-bouma — APPROVED** [review]
Looks good to me, although it may be worth @MijnheerD validating that it works once more : )

**Comment by MijnheerD** [comment]
Yes, this solves #657 , thanks!

**Review by MijnheerD — APPROVED** [review]

**Comment by MijnheerD** [comment]
Actually, I am afraid I have to come back to this. I think I only received the change from commit 633cc151b193674aa3bc54adeac5c636befaece4 now (because I merged develop back into our lofar/development branch), so I was always working with the Detector class instead of the function variant. 

Now I am having a bunch of problems because stuff is not correctly imported from the `.nur` file. The Detector time is not longer set and the `self._antenna_by_depth` keyword is reset (which is very annoying when trying to load antenna models). Not sure how this can be addressed?

**Comment by sjoerd-bouma** [comment]
@MijnheerD I am slightly surprised if that is a new issue, because I don't think that has changed. It is however a good point - it would be much more convenient if the detector time and the antenna_by_depth kw would also be stored when storing the detector in the nur file.

**Comment by MijnheerD** [comment]
@sjoerd-bouma The reason this is new to me, is because I was testing the hotfix on our lofar branch, which was not up to date with develop. Therefore, I was still working with the class implementation of Detector instead of the function variant. I am not sure what changed, but somehow with the class variant before I was not encountering the issues with the keyword not being set (this is most notable when loading antenna patterns, because when the `antenna_by_depth` kw is kept to True, there is something append to the name which makes it incompatible with our LOFAR antenna pattern name).

**Comment by fschlueter** [comment]
Hi both, I will try to have a look at this. This is indeed a problem (at least for the antenna depth key word). I think the detector time should be actually set to None which would require to call an `det.update`

**Comment by fschlueter** [comment]
I have know I idea why it worked before though. Are you sure it worked before @MijnheerD ?

**Comment by sjoerd-bouma** [comment]
@fschlueter @MijnheerD I would be somewhat surprised if there was no need to call `update` before. The `antenna_by_depth` keyword was also not set previously, but would have defaulted to `False` instead of the current `True`, so that would have 'worked'. 
Obviously it would still be preferable to have both stored correctly, but as far as I'm concerned that does not need to happen in this PR, as it is a separate issue (if you do decide to include it in this PR that's also fine by me).

**Comment by fschlueter** [comment]
Arg, I did change the default behaviour? This is bad of course.... @sjoerd-bouma  do we store the keyword in the existing nur files (does not look like it on a first glance)

**Comment by sjoerd-bouma** [comment]
> Arg, I did change the default behaviour? This is bad of course.... @sjoerd-bouma do we store the keyword in the existing nur files (does not look like it on a first glance)

No, this change predates you - originally the Detector and GenericDetector classes were separate, and had different default arguments for `antenna_by_depth`. At some point the Detector class was moved to detector_base and Detector would automatically be able to decide if an imported detector was a generic detector or not, which simplified life a lot, but this also meant that their default arguments were unified.

As far as I can tell the initialization arguments and detector time have never been stored in the nur files. I agree with @MijnheerD that they should be, though.

**Comment by fschlueter** [comment]
Fine. I suggest we merge this and open an new PR for this. @MijnheerD would you mind creating a short Issue and assign me?

**Pull request merged**
