### PR TITLE
improved validation workflow

### PR DESCRIPTION
**Pull request by cg-laser**
all test are executed even if some show an error

### CODE REVIEW

**Review by anelles — APPROVED** [review]
Looks like you just added an always() everywhere, so that is fine with me. Not sure how these workflows work exactly. 
But one comment while reading this: While do we uninstall numba to test ARZ? Shouldn't we test it with it? (line 33)

**Comment by anelles** [comment]
The I don't understand how this file works. It looks that the installation dependencies are always the same.

**Comment by cg-laser** [comment]
```
- name: Single event test (ARZ)
      if: always()
      run: |
        export GSLDIR=$(gsl-config --prefix)
        export PYTHONPATH=$(pwd):$PYTHONPATH
        NuRadioMC/test/SingleEvents/validate_ARZ.sh
    - name: Test Numba version of ARZ
      if: always()
      run: |
        export GSLDIR=$(gsl-config --prefix)
        export PYTHONPATH=$(pwd):$PYTHONPATH
        pip install numba
        NuRadioMC/test/SingleEvents/validate_ARZ.sh
```

**Comment by anelles** [comment]
Ah, I fell for the double negative. First uninstalling and then installing again. Never mind. All clear.

**Pull request merged**
