### PR TITLE
Fix doc strings which cas deployment of docu to fail

### PR DESCRIPTION
**Pull request by fschlueter**
Sometimes the deployment of the doc strings is skipped sometimes not (and then it fails). Not sure why but maybe we just fix it.

### CODE REVIEW

**Comment by shallmann** [comment]
Hmm.. don't know about the documentation, but the `Deploy Documentation / build (pull_request) ` seems to be skipped and does not run through when kicked manually if I am not mistaken?

**Review by shallmann — APPROVED** [review]
These changes are all ok to me

**Comment by fschlueter** [comment]
Did you init it manually now?

**Review by sjoerd-bouma — APPROVED** [review]
Thanks Felix!
@shallmann - the documentation test (build) is run on either `push` or `pull request`, in this case because it runs on `push` it skips the one on pull request.

FYI, having underlines too long (rather than too short) raises an error only with numpydoc>=1.2, I was too lazy to fix all of them previously, which is the reason we stuck with numpydoc 1.1. Maybe we can upgrade now, if they're all fixed?

**Comment by fschlueter** [comment]
> FYI, having underlines too long (rather than too short) raises an error only with numpydoc>=1.2, I was too lazy to fix all of them previously, which is the reason we stuck with numpydoc 1.1. Maybe we can upgrade now, if they're all fixed?

Why was I getting an error than?

**Pull request merged**
