### PR TITLE
Add interferometric reconstruction

### PR DESCRIPTION
**Pull request by fschlueter**
Hi guys, (@anelles , @cg-laser , @christophwelling)
i was asked to add my interferometric reconstruction of air showers here.

I leave this early PR here for you to comment. Is it okay to have two classes (i.e. modules) in one file? Is it fine that one inherits for the other? Right now, the reconstruction only runs on sim showers. The reconstruction of the depth Xrit needs an shower axis as input. Besides that it can be easily extended to run on measured events. The axis reconstruction needs some more thinking i guess. I briefly tested both modules with some of my (inclined) air showers, everything seems to work.  
There are many things to improve. After I am back from my holidays, I am happy to gradually improve the code. Any comments are highly appreciated. 

This branch contains already the first commit of #309 and will need a rebase once #309 is merged.
Cheers

### CODE REVIEW

**Comment by anelles** [comment]
I think your module should have a short description, just in the run function. You have already added the example, so I would think that expanding on this with a readme would be helpful. It is really up to you whether you want an additional file or instructions in the .py file. We don't have a standard there.

**Comment by fschlueter** [comment]
hm was it a good idea/the correct way to rebase onto develop? Now we have a lot of commits in here which are not related. I thought git(hub) understands this.

**Comment by fschlueter** [comment]
@sjoerd-bouma, locally `python make_docs.py` runs through (with some error msgs though). What is going wrong, How can I reproduce this locally?

**Comment by sjoerd-bouma** [comment]
@fschlueter the latest version of `numpydoc` introduced a new warning that broke `make_docs.py`. I haven't had time to fix this properly, but PR #377 fixed the `numpydoc` version to `1.1.0` to allow the documentation test to run successfully. If you merge the latest `develop` it should now be fine.

**Review by anelles — DISMISSED** [review]
Thanks for updating the docstrings! I think some of the helper functions could still use some, but they are relatively straight forward.

**Review by cg-laser — APPROVED** [review]

**Pull request merged**
