### PR TITLE
New tests

### PR DESCRIPTION
**Pull request by anelles**
Adding Veff test for built-bot

### CODE REVIEW

**Comment by cg-laser** [comment]
you can check pyproject.toml in NuRadioMC and NuRadioReco for all required non-standard packages

**Comment by anelles** [comment]
As shown here, the test fails in 5% of the time. I guess for now this is fine, as typically both the branch and the pull request is built close after each other.

**Comment by anelles** [comment]
> packages

This is not enough for the built-bot. It literally has nothing, no even numpy.

**Comment by anelles** [comment]
By the way, I reran the test and now it is 19% different. This is a bit cumbersome ...

**Comment by cg-laser** [comment]
I thought more about @christophweeling idea to fix the seed. I think this is a good idea, although it does not work for certain cases where we change something in the event gen that alters the random sequence. For these cases we will need to life with the limited statistical precision, but the rest should result in an identical result. 

I don't have time to fix it before my vacation, so I'm already approving the pull request as it already works fine as it is, and this optimization can be done later.

**Comment by anelles** [comment]
@cg-laser I don't think you actually approved this before leaving for vacation. So I will just use my priviliges to merge to move ahead.

**Pull request merged**
