### PR TITLE
Fix indices in simulation.py

### PR DESCRIPTION
**Pull request by lpyras**
This PR addresses issue https://github.com/nu-radio/NuRadioMC/issues/391 Wrong showers written to station_xxx substructure in .hdf5 output.
Reason for this was a wrongly defined function find_indices. This function is now replaced in line 1025.
I suggest replacing the variables local_shower_index and global_shower_index are replaced by event_indices_of_triggered_shower_in_eventgroup and shower_indices_of_triggered_showers. They are too long, please make suggestions.
I also added to entries to each station: 'event_id_per_shower' and 'event_group_id_per_shower' which should make it easier to match information of station level to a single particle event.

A test to check if launch_vectors are NaN is not implemented yet.

### CODE REVIEW

**Comment by shallmann** [comment]
I think this simple example shows that the function that was in there did not do the right thing:
[
Screenshot 2022-11-01 at 13 31 06
](url)

**Review by cg-laser — COMMENTED** [review]
thanks for fixing this! It seems to do the right thing. I didn't approve it yet because I think I went to this more complicated approach because the solution you implemented is slow. The arrays can be huge and you have a loop in there. This potentially slows down the simulation. Did you do any tests about the speed?

**Comment by shallmann** [comment]
@cg-laser no we didn't benchmark it. @lpyras can you check?

(I don't recall if we need to keep ordering / duplicates from the `for` loop? Otherwise `np.argwhere(np.isin(event_indices, global_shower_indices)))` potentially with `assume_unique=True` may be slightly faster)

**Review by cg-laser — DISMISSED** [review]

**Comment by cg-laser** [comment]
good point. The shower indices are unique. If you could run a speed comparison between the different methods, that would be great. The arrays should be at least 10k long.

**Comment by lpyras** [comment]
> good point. The shower indices are unique. If you could run a speed comparison between the different methods, that would be great. The arrays should be at least 10k long.

I checked, typical times for 10k showers are
time for loop  0.0031s
time for array  0.0018s
The array is a ~1.5x faster, therefore I implemented Steffens suggestion. The output of both solutions is equal.

**Review by cg-laser — APPROVED** [review]
thanks! Timing looks ok now. Thank for checking.

**Comment by fschlueter** [comment]
Hi, I want to check for the TDR simulations how many radio events were triggered not by the first interaction (similar to what you did in https://arxiv.org/abs/2003.13442 Fig. 9 & 11) . Can I use shower_id  to do this? As far as I understand is the bug preventing this? If not, is there any other way of doing it and was this bug present for the paper above?

**Comment by fschlueter** [comment]
event_group_id_per_shower would have been handy now :)]

**Comment by fschlueter** [comment]
> Hi, I want to check for the TDR simulations how many radio events were triggered not by the first interaction (similar to what you did in https://arxiv.org/abs/2003.13442 Fig. 9 & 11) . Can I use shower_id to do this? As far as I understand is the bug preventing this? If not, is there any other way of doing it and was this bug present for the paper above?

Ah... I realised that I do not need the information on the station level.... sorry for the noise

**Pull request merged**
