### PR TITLE
Docu/antenna model

### PR DESCRIPTION
**Pull request by shallmann**
Updates antenna model names to match the ones available on the cluster.

### CODE REVIEW

**Comment by shallmann** [comment]
I want the models listed here to reflect what is on the server - We were just asked the ~5th time why a certain antenna model can not be loaded - the reason always being missing `n`'s or slightly different filenames.
 
Not sure who is best to review these changes - the changes I made should change adjust filename changes to reflect what is on the cluster;
I am not the right person to revisit existing documentation for existing models, and add new documentation to the additional models.

**Comment by shallmann** [comment]
@anelles do you have a suggestion who might fill in information on the models without documentation? If we don't I would tend to just merge it - non-detailed documentation is certainly less confusing than wrong documentation

**Comment by anelles** [comment]
If I am not mistaken, all the bicone models are from Chicago, likely @dansmithphysics ? The LPDA models should be from UCI, but probably only @cg-laser and @ggaswint know details. 
Yes, I think we maybe a bit late in this game for thorough documentation. SO unless there is suddenly a flurry of activity,  I agree, it is more useful to merge and  create an issue.

**Comment by dansmithphysics** [comment]
Hi all, 

The RNO-G dipole antennas are saved in a repo here: https://github.com/dansmithphysics/rnog_vpol_fat_dipole. There is some amount of documentation and simulation output on them here: https://radio.uchicago.edu/wiki/index.php/Science_Antennas#Downhole_V-Pol_Antenna 

I have a lot less information on the ARA bicones, but I did import the model into xFDTD (but was never able to simulate it since they were very slow simulations). Those files are saved here: https://github.com/dansmithphysics/ara_bicone

Hope that helps!

**Comment by christophwelling** [comment]
While we are talking about missing antenna models, there is also this issue: #420  about a missing antenna model in one of the detector descriptions.

**Comment by shallmann** [comment]
Ok, from @dansmithphysics linked repos I don't see additional information that could be put into the documentation now. The KU_dipole is a separate issue, but worth following up. Will merge the updated antenna documentation as is.

**Pull request merged**
