### PR TITLE
Decay muons

### PR DESCRIPTION
**Pull request by daniel-zid**
The code has been refactorised, the units are now handled more properly and there is a class with private methods that use Proposal units, so as to avoid units problems. The muons coming from the decay of taus are now propagated and their showers stored.

### CODE REVIEW

**Comment by cg-laser** [comment]
Ok then its fine. I was worried that we need some heavy pre calculations to be able to use proposal. 

One solution that one typically does is to have a "*.config.sample" file. The user is then supposed to make a copy to "*.config" where he adjusts the paths. The "*.config" files will not be tracked by git. This way every user can have their custom paths in the config file. 
The problem now is that I would need to adjust the path, but then I would always have an uncomitted change. If I wanted to change some other setting and commit it, it would not be possible.

**Comment by daniel-zid** [comment]
I've deleted the config files and added the config.sample files, together with comments and an error message that explains the way they should be changed. Let me know if you like it.

**Comment by cg-laser** [comment]
can you add the config files to a ".gitignore" file? You might need to create it first. So that the user config files do not show up in git.

**Comment by daniel-zid** [comment]
I did not know one could do that. Tell me if that's what you wanted. I've included a .gitignore file for all the config*json files.

**Comment by cg-laser** [comment]
looks good to me. Now the *.json files should not show up when you do a `git status .`

**Pull request merged**
