### PR TITLE
Store non-triggered events if config save_all is true

### LINKED ISSUE #438: The config "save_all" does not seem to work
From the description if set to `True` also non-triggered events should be stored. However this is not the case. In fact I do not see `save_all` to be anywhere used.

### PR DESCRIPTION
**Pull request by fschlueter**
Fixes #438 

This change seems to fix the issue. However, I have just re-run a simulation and saw that more events are written out! Also, event which skipped to speedup the simulation are still not stored. Is that desired? Is that information in the hdf5 files? I am not experience yet to judge whether the use case is strong enough, but  I would like to have possibilities to have all events stored (even if their signals are not properly simulated to speed up the simulation), this could be useful for efficiency calculation, right?

### CODE REVIEW

**Comment by fschlueter** [comment]
shall I do some refactoring in the MR or better in a separated one?

**Comment by fschlueter** [comment]
Oh apparently is `save_all` not in the default_config. Was this option removed because it is undesired or was this feature never really implemented and should be removed from  the manual?

**Comment by anelles** [comment]
I remember that we have discussed this previously. I am not sure whether we have come to a conclusion what the intention of "all" actually was -- like which events are still skipped etc. 
Maybe something to discuss more widely.

**Comment by cg-laser** [comment]
A few general comments. 

- All events are present in the input hdf5 file, so you can check that file if you need it. 
- the total number of generated neutrino interactions are still present in the output hdf5 file, so you can still calculate efficiencies, effective areas etc. just fine. 
- to get effective areas as a function of zenith angle for example, you can run simulations for separate zenith angle bins, or you just bin your results aftewards. As one should always start with isotropic incoming directions, this can be achieved easily and Steffen already implemented this rebinning in the Veff tool. 
- speedup cuts can be disabled by adapting the settings in the config file

There was a reason why we removed this feature but I don't recall why exactly. I think the problem was with secondary interactions where one neutrino interaction generates many showers where we don't have a 1:1 mapping to events.

**Comment by cg-laser** [comment]
I remember the problem now. For simulations with secondaries, there will be many many showers along the muon/tau track. If all these showers are considered, it will result in a single event with a very long trace. Remember that events are created dynamically depending on the time separation between the pulses arriving at the DAQ. If all showers are considered, there will likely not be a sufficiently large time delay to create separate events.

**Pull request closed without merging**
