### PR TITLE
Signal visualization

### PR DESCRIPTION
**Pull request by christophwelling**
I wrote a little app to show what our neutrino signals will look like.
You run it like the NuRadioReco eventbrowser: 
`python3 index.py`
Then open a browser and go to the url shown in the output.
It already includes the amplifiers for RNO, so you either need to run it with the RNOG_hardware_response branch on NuRadioReco or wait for it to be merged.

### CODE REVIEW

**Comment by cg-laser** [comment]
cool, can you add a screenshot?

**Comment by christophwelling** [comment]
Screenshot from 2020-03-09 09-46-10
Sure, but you don't actually need any input files to try it for yourself

**Comment by christophwelling** [comment]
Could someone please approve this?

**Comment by cg-laser** [comment]
sry, I will have a look later today.

Am 19.03.20 um 09:02 schrieb christophwelling:

**Comment by cg-laser** [comment]
Hi Christoph, finally my review. Awesome app!!! This is super useful and cool. We might even want to make this publically available at some point for outreach. 

I have a few minor comments though. 
- can you add the information what filter is being used? (as a tooltip when you hover over filter?)
- Can you increase the frequency range of the spectrum plots? Maybe make it configurable via a slider? 500MHz is too small for many purposes. It its not possible to make it configurable, maybe increase it to at least 1GHz. 
- the signal is always only eTheta polarized. Hence, the Hpol can not be visualized (or rather only its cross pol component is used). Can you add a slider to change the polarization ratio from fully eTheta to fully ePhi? 
- can you zoom in into the time trace a bit more as default? Even at low frequencies, the pulse is only a few nanoseconds long. 

Thanks a lot

**Comment by christophwelling** [comment]
Update:
- Sampling rate is configurable between 1 and 5 GHz.
- Traces are zoomed in to show the 100ns around the maximum
- Added tooltips for filter, amplifier and antenna
The slider for the polarization angle was already there, below the one for the viewing angle.
I don't have a server to run this on, but feel free to deploy it if you have one.

**Comment by cg-laser** [comment]
Awesome, thanks! Just two more things: 

Can you allow the filter up to at least 1 GHz? 
Can you add a tooltip for the polarization angle? The definition is not clear to me.

Not sure how to solve this, but could we make the layout of the plots more compact that one can see at least the efield and voltage plots at the same time? On the other hand you want the antenna response plot next to the antenna and amplifier settings sliders, so I'm not sure if this is possible.

**Comment by christophwelling** [comment]
I added a tooltip for the angles and extended the filter range. Changing the layout is more work, so I'm  going to leave that as it is.

**Comment by cg-laser** [comment]
thanks Christoph!

**Pull request merged**
