### PR TITLE
Remove deprecated interface from visualize_detector.py; Update RNO_single_station.json 

### PR DESCRIPTION
**Pull request by fschlueter**
Not sure if this tool is very useful and if the fix really makes sense. Also, if the tool is useful should we added to the CI?

### CODE REVIEW

**Comment by anelles** [comment]
I would like @iplaisier to comment on this. I think she mostly handled the RNO-G json. Is this a useful tool?
My feeling is that I wouldn't add it to CI -- it may be useful but not that important.

**Review by cg-laser — APPROVED** [review]
I think it is a useful feature to generalize the script. Users can still adapt it to take a different station.

**Review by cg-laser — COMMENTED** [review]
But I'm not sure about the renaming of the RNO-G detector description. Shouldn't this be better done in a separate PR?

**Comment by fschlueter** [comment]
@cg-laser I updated the MR title to reflect the fact that I fix the json file. I dont not think such a uncritical change needs to be an own PR.

**Pull request merged**
