### PR TITLE
GENIE-HEDIS cross sections for isoscalar (w/o Glashow)

### PR DESCRIPTION
**Pull request by shallmann**
fit to isoscalar xsections calculated with the GENIE module HEDIS (HEDIS-BGR) using parameterisation of the 'CTW' (Connolly et al.) xsec.

I am still waiting for input from the author (arXiv:2004.04756) for HEDIS-AABGR, but overall differences to CTW is small.

This pull request is to discuss neutrino regeneration in the Earth. In the paper they present code to calculate absorption/transmission of UHE neutrino fluxes in the Earth including regeneration.
It seems that re-generation (depending on the assumed spectrum) could be relevant to include in NuRadioMC?

### CODE REVIEW

**Comment by shallmann** [comment]
screenshot 2020-12-10 at 14 29 32

I suggest to leave this pull request open, until I have feedback from the author, but it should be possible to calculate spline tables for different spectral indices to include in the earth attenuation.

**Comment by anelles** [comment]
How is this already in conflict with the master?

**Comment by anelles** [comment]
And yes, tau regeneration should be relevant at our energies, but no one had the time to implement it and we always said that we should include it at some point ...

**Comment by shallmann** [comment]
> How is this already in conflict with the master?

Christian added uncertainties to the CTW in parallel, therefore the conflict... Let's postpone this to next week.
I have in the meanwhile also got the GENIE xsecs calculated with AABGR scheme (better top mass treatment), and got instructions from the author how to best calculate / include regeneration.

**Comment by anelles** [comment]
I assume we simply want to merge the two updates?

**Review by anelles — DISMISSED** [review]

**Comment by shallmann** [comment]
This branch still was super outdated and tried to merge to master. Will start new pull request from branch #add_hedis_bgr_xsection_from_develop

**Pull request closed without merging**
