### PR TITLE
Unified documentation

### PR DESCRIPTION
**Pull request by christophwelling**
Sets up a unified documentation for NuRadioReco and NuRadioMC. I copied over the NuRadioReco documentation and set up the NuRadioMC documentation generated from the docstrings.
The instructions from the NuRadioReco "How to contribute" page basically still work, only the file structure is set up a bit differently. 

The documentation is already deployed at https://nu-radio.github.io/NuRadioMC/main.html

Feel free to add more documentation or port over the wiki, especially for NuRadioMC

### CODE REVIEW

**Comment by boboeyen** [comment]
I've added the documentation for the raytracing and the ice models

**Comment by boboeyen** [comment]
I've moved all the wiki pages indicated as manual (including ice models and raytracer)

**Review by anelles — APPROVED** [review]
Looks good to me. Is this now automatically deployed somehow or does it still need manual intervention?

**Comment by christophwelling** [comment]
Haven't gotten around to implementing that yet, but it's on my agenda

**Comment by christophwelling** [comment]
Okay, after this branch is merged, a push to develop will automatically trigger an update of the documentation.

**Comment by anelles** [comment]
Ok, I will have to believe you ;)
If you fix the conflict, then I am happy to approve. 
Also please take a look at the test failing .. not sure that this was you.

**Comment by christophwelling** [comment]
I accidentally pulled from master instead of develop. Old habits...

**Review by anelles — APPROVED** [review]

**Comment by sjoerd-bouma** [comment]
I think it would be useful to merge this sooner rather than later, but it looks like there is a lot of cleanup that should still be done...
- Compiling this for the first time, I get a _lot_ of warnings. No errors, and presumably most of them are cosmetic (badly formatted lists etc.). I imagine no one wants to spend a couple of days fixing this stuff. As a lot of things seem to be outdated / illogically structured as well, I guess this will just have to go on the 'To Do' list that hopefully people will occasionally contribute to.
- (one of these things is that a bunch of .png files seem to be missing?)
- On that topic - the how to contribute section should also explain how to add documentation more clearly. Again, I'm happy to do this later, also once I've figured out how sphinx works
- NuRadioReco/antennamodels.rst is currently not included in any toctree. I tried to add it and restructure the detector description, but the latter brings me to the next point...
- Internal links are currently done by pointing at htmls. As far as I can tell, this does not raise errors/warnings if links can not be found (could have missed this, there's only the 275 of them to scroll through). This _will_ break things if pages are moved / headings are adjusted etc. [Sphinx seems to recommend cross-referencing instead](https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html). That way, at least once you change something, you'll be told if it breaks links elsewhere. Of course, that also means _all_ internal links have to be replaced...

For now, I still think this should just be merged, so at least it becomes a shared headache, as opposed to only Christoph's. Just be aware there's a pretty long to-do list attached...

**Comment by sjoerd-bouma** [comment]
Re the above - it seems pngs are missing because they're excluded by .gitignore. This can probably be remedied by adding another .gitignore in the documentation folder with the line `!**/*.png`. I don't actually have the pngs that are missing, maybe @christophwelling can add them. The missing files seem to be
```
logo_small.png
NuRadioReco/pages/detector/orientation_sketch.png
NuRadioReco/pages/event_structure.png
```

Another remark - I don't think the `pip` version of NuRadioMC is used much, but if we want to take the pip version seriously, _probably_ both master & develop should deploy documentation? I'll file this under 'to-do' for now...

**Comment by christophwelling** [comment]
Can someone review this again so we can merge?

**Review by anelles — APPROVED** [review]

**Comment by sjoerd-bouma** [comment]
I'm still working on this
We discussed this on Thursday... I'll try to finish it today but I keep running into issues with sphinx.

**Pull request merged**
