### PR TITLE
Adding cython and trying to fix the built-bot

### PR DESCRIPTION
**Pull request by anelles**

### CODE REVIEW

**Comment by anelles** [comment]
@cg-laser The GSL installation works now. The files are still different, while they are the same on my machine. You are up. I am out of ideas

**Comment by cg-laser** [comment]
@clark2668, we set up a thorough built bot for NuRadioMC and found that the ray tracing solution is slightly different at the level of 1e-6. When we change the validation to this level of precision everything is fine, but I was wondering if we can't increase the C++ ray tracing precision. 
Would it be possible to just increase the fitting precision? I know that you did quite some testing with that but I didn't remember what you conclusion was. So I though you might want to chime in
The interesting thing is that on my and Annas mac we get perfect agreement, but the built bot (running on ubuntu) shows small deviation. So maybe this is a platform thing.

**Comment by anelles** [comment]
@cg-laser do we then get perfect agreement on all platforms for the python ray tracer?

**Comment by daniel-zid** [comment]
We've checked that on the Zeuthen cluster (Unix) the results are not the same either. Mismatch sample:

Mismatch: 46.2%
Mismatch: 41.9%
Mismatch: 38.1%

**Comment by cg-laser** [comment]
@daniel-zid can you post the full output? Are only three arrays different?

**Comment by clark2668** [comment]
Hi all, catching up here. I don't think I fully understand the problem: can you be more specific about where you get disagreement? Like, in the value forC0, or in the time of flight, etc?

Also Daniel, are you seeing that discrepancy for the c++ or python implementation?

**Comment by cg-laser** [comment]
We already see disagreement in the C0 parameters. And then of course in all derived quantities

--

**Comment by clark2668** [comment]
Okay, gotcha. I'll try to take a look soon.

**Comment by daniel-zid** [comment]
Hi everyone,

@clark2668 I'm using the C++ implementation

@cg-laser No, that was just a sample. All the arrays are different. And it looks like I was using an old version of the test, maybe. Here's the full output:

Testing the files 1e18_output.hdf5 and 1e18_output_reference.hdf5 for equality

array azimuths not equal

Arrays are not equal

(shapes (195,), (10,) mismatch)
 x: array([5.66725 , 2.636737, 5.746159, 6.257823, 0.192388, 5.421533,
       3.944117, 3.649779, 2.583087, 1.349493, 1.001334, 2.672811,
       0.415002, 3.871086, 5.994723, 0.132709, 3.644493, 1.702431,...
 y: array([5.49571 , 1.496179, 5.784032, 2.076945, 2.792561, 2.913047,
       2.928875, 4.009066, 0.388627, 4.689754])

array energies not equal

Arrays are not equal

(shapes (195,), (10,) mismatch)
 x: array([1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,
       1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,
       1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,...
 y: array([1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,
       1.e+18, 1.e+18])

array event_ids not equal

Arrays are not equal

(shapes (195,), (10,) mismatch)
 x: array([  62,   93,  127,  220,  257,  261,  499,  638,  652,  728,  740,
        866,  913,  932,  976,  992, 1067, 1224, 1236, 1237, 1397, 1415,
       1454, 1512, 1546, 1641, 1662, 1670, 1716, 1818, 1844, 1948, 1991,...
 y: array([106, 127, 129, 144, 169, 177, 259, 328, 516, 658])

array flavors not equal

Arrays are not equal

(shapes (195,), (10,) mismatch)
 x: array([-14,  16,  14, -14,  12, -14,  16, -12, -12,  12,  12,  16,  16,
       -16,  16,  14,  12, -14, -12, -12,  12, -14, -14,  14, -12, -12,
        16,  12,  12,  14, -12,  14, -12,  12,  16, -12, -16, -12,  12,...
 y: array([-12, -14,  16, -12,  12,  16, -14,  12,  14,  12])

array inelasticity not equal

Arrays are not equal

(shapes (195,), (10,) mismatch)
 x: array([4.044951e-01, 5.125398e-03, 8.696499e-01, 1.494705e-01,
       8.144427e-01, 7.850035e-01, 9.778851e-01, 8.810840e-02,
       5.429715e-01, 1.058757e-02, 2.506339e-02, 8.712642e-01,...
 y: array([9.606599e-01, 2.382346e-01, 1.121082e-01, 1.332058e-04,
       2.798942e-01, 5.415147e-01, 1.323083e-01, 7.875944e-01,
       5.110236e-01, 1.896198e-01])

array interaction_type not equal

Arrays are not equal

(shapes (195,), (10,) mismatch)
 x: array(['cc', 'cc', 'nc', 'nc', 'cc', 'cc', 'cc', 'cc', 'cc', 'cc', 'cc',
       'cc', 'nc', 'cc', 'cc', 'nc', 'cc', 'cc', 'nc', 'cc', 'cc', 'cc',
       'cc', 'cc', 'cc', 'nc', 'cc', 'nc', 'cc', 'cc', 'cc', 'nc', 'nc',...
 y: array(['nc', 'cc', 'cc', 'cc', 'cc', 'nc', 'cc', 'cc', 'nc', 'cc'],
      dtype='|S2')

array multiple_triggers not equal

Arrays are not equal

(shapes (195, 3), (10, 3) mismatch)
 x: array([[ True, False,  True],
       [ True, False,  True],
       [ True, False,  True],...
 y: array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],...

array n_interaction not equal

Arrays are not equal

(shapes (195,), (10,) mismatch)
 x: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
 y: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

array triggered not equal

Arrays are not equal

(shapes (195,), (10,) mismatch)
 x: array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,...
 y: array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

array weights not equal

Arrays are not equal

(shapes (195,), (10,) mismatch)
 x: array([3.764273e-02, 1.064286e-02, 1.632478e-04, 1.567131e-04,
       1.000000e+00, 3.801332e-03, 1.000000e+00, 1.406264e-02,
       6.908667e-05, 1.817229e-01, 2.737602e-02, 1.000000e+00,...
 y: array([1.      , 0.231935, 1.      , 0.002499, 1.      , 0.006582,
       1.      , 0.16554 , 1.      , 1.      ])

array xx not equal

Arrays are not equal

(shapes (195,), (10,) mismatch)
 x: array([ 1533.428199,  -781.458293,   164.593807,   227.754813,
         986.697079,  1119.89151 ,  -395.348702, -1265.349076,
        -612.072184,   274.739849,   636.768817, -1666.860243,...
 y: array([  782.98583 ,    66.381989,   676.304394,  -344.61053 ,
       -1136.538466,  -640.696346, -1364.757291,  -682.07755 ,
        1039.201163,   -19.802948])

array yy not equal

Arrays are not equal

(shapes (195,), (10,) mismatch)
 x: array([  -24.338915,  -218.92764 , -1401.252484,  -710.219671,
        1596.465143,  -400.836104,  -920.62777 ,   242.853817,
         403.687066,   387.982638,  1196.577887,   118.640521,...
 y: array([-786.245259,  887.980856, -368.723243,  621.689372,  413.621652,
        149.032365,  294.767297, -804.350657,  425.501689, -874.749518])

array zeniths not equal

Arrays are not equal

(shapes (195,), (10,) mismatch)
 x: array([1.674443, 1.6965  , 1.79839 , 1.812965, 1.448679, 1.728279,
       1.549356, 1.696045, 1.835344, 1.621549, 1.678043, 1.523791,
       1.641773, 1.795624, 1.45412 , 1.385769, 1.834123, 1.69118 ,...
 y: array([1.394383, 1.616912, 1.52525 , 1.739107, 1.385625, 1.707295,
       1.35697 , 1.624328, 1.486067, 1.358707])

array zz not equal

Arrays are not equal

(shapes (195,), (10,) mismatch)
 x: array([-1692.241049,  -773.159055, -2185.974355,  -912.234438,
       -1736.449495, -2326.829447, -1912.746837, -2212.149582,
       -2283.337586,  -498.202858, -2128.062721, -1639.590007,...
 y: array([-1154.650964, -1408.23212 ,  -949.238124, -1408.556918,
       -1166.357588, -1397.190584, -1329.708666, -1590.843091,
       -1286.589363,  -999.394728])

array SNRs of group station_101 not equal

Arrays are not equal

(shapes (195,), (10,) mismatch)
 x: array([1.181577e+00, 1.555353e-01, 5.388849e-01, 4.968380e-02,
       3.579527e-01, 7.950569e-01, 4.809782e-01, 2.327827e-01,
       1.414324e+00, 4.653972e+00, 5.423971e-01, 3.774638e+00,...
 y: array([26.765744,  4.176577,  5.12592 ,  8.00887 , 25.793275,  8.348002,
        2.244255, 10.030801, 10.458018,  3.493762])

array launch_vectors of group station_101 not equal

Arrays are not equal

(shapes (195, 8, 2, 3), (10, 8, 2, 3) mismatch)
 x: array([[[[-0.66226 ,  0.010491,  0.749201],
         [-0.661437,  0.010478,  0.749927]],
...
 y: array([[[[-0.479626,  0.479785,  0.734687],
         [-0.478771,  0.478929,  0.735803]],
...

array maximum_amplitudes of group station_101 not equal

Arrays are not equal

(shapes (195, 8), (10, 8) mismatch)
 x: array([[1.633711e-04, 1.503912e-04, 1.584695e-04, ..., 1.210316e-05,
        1.149514e-05, 1.101981e-05],
       [4.181202e-05, 4.916673e-05, 3.885446e-05, ..., 1.213558e-06,...
 y: array([[8.160554e-05, 6.796814e-05, 7.088822e-05, 7.655756e-05,
        2.178900e-04, 2.141058e-04, 1.931431e-04, 2.496268e-04],
       [5.411802e-05, 5.797517e-06, 5.429174e-05, 5.944374e-06,...

array maximum_amplitudes_envelope of group station_101 not equal

Arrays are not equal

(shapes (195, 8), (10, 8) mismatch)
 x: array([[2.072564e-04, 1.999324e-04, 2.083193e-04, ..., 1.227396e-05,
        1.208298e-05, 1.173782e-05],
       [5.383569e-05, 5.060950e-05, 5.099858e-05, ..., 1.527266e-06,...
 y: array([[8.178126e-05, 7.472673e-05, 7.180732e-05, 7.830200e-05,
        2.859568e-04, 2.732714e-04, 2.835147e-04, 2.946413e-04],
       [6.015839e-05, 6.146214e-06, 6.007043e-05, 5.949502e-06,...

array multiple_triggers of group station_101 not equal

Arrays are not equal

(shapes (195, 3), (10, 3) mismatch)
 x: array([[ True, False,  True],
       [ True, False,  True],
       [ True, False,  True],...
 y: array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],...

array polarization of group station_101 not equal

Arrays are not equal

(shapes (195, 8, 2, 3), (10, 8, 2, 3) mismatch)
 x: array([[[[-3.555192e-01, -7.112182e-01, -6.064444e-01],
         [ 3.343651e-01, -7.217122e-01, -6.060788e-01]],
...
 y: array([[[[-0.322874,  0.31982 , -0.890768],
         [ 0.321908, -0.325172, -0.889179]],
...

array ray_tracing_C0 of group station_101 not equal

Arrays are not equal

(shapes (195, 8, 2), (10, 8, 2) mismatch)
 x: array([[[0.848198, 0.849253],
        [0.849077, 0.850133],
        [0.849991, 0.851047],...
 y: array([[[0.828114, 0.829595],
        [0.828111, 0.829591],
        [0.829711, 0.831193],...

array ray_tracing_C1 of group station_101 not equal

Arrays are not equal

(shapes (195, 8, 2), (10, 8, 2) mismatch)
 x: array([[[3217.411644, 3213.819753],
        [3214.416226, 3210.837853],
        [3211.316586, 3207.752109],...
 y: array([[[2042.737978, 2038.794593],
        [2042.746805, 2038.803357],
        [2038.485283, 2034.571914],...

array ray_tracing_solution_type of group station_101 not equal

Arrays are not equal

(shapes (195, 8, 2), (10, 8, 2) mismatch)
 x: array([[[1., 3.],
        [1., 3.],
        [1., 3.],...
 y: array([[[1., 3.],
        [1., 3.],
        [1., 3.],...

array receive_vectors of group station_101 not equal

Arrays are not equal

(shapes (195, 8, 2, 3), (10, 8, 2, 3) mismatch)
 x: array([[[[ 0.86957 , -0.013775, -0.493618],
         [ 0.86849 , -0.013758,  0.495516]],
...
 y: array([[[[ 0.629766, -0.629974, -0.454454],
         [ 0.628642, -0.62885 ,  0.457556]],
...

array travel_distances of group station_101 not equal

Arrays are not equal

(shapes (195, 8, 2), (10, 8, 2) mismatch)
 x: array([[[2287.351794, 2289.019131],
        [2285.354162, 2287.021227],
        [2283.290372, 2284.957173],...
 y: array([[[1604.735324, 1606.386016],
        [1604.741503, 1606.392197],
        [1601.764299, 1603.413916],...

array travel_times of group station_101 not equal

Arrays are not equal

(shapes (195, 8, 2), (10, 8, 2) mismatch)
 x: array([[[13413.11965 , 13417.554365],
        [13401.528778, 13405.977894],
        [13389.553253, 13394.017241],...
 y: array([[[ 9353.236638,  9357.32003 ],
        [ 9353.272062,  9357.355392],
        [ 9336.200852,  9340.314141],...

array triggered of group station_101 not equal

Arrays are not equal

(shapes (195,), (10,) mismatch)
 x: array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,...
 y: array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

**Comment by clark2668** [comment]
I'm confused now--could the difference just be a problem with the tests? Or maybe @daniel-zid point is unrelated to the other discussion.

**Comment by cg-laser** [comment]
@daniel-zid something must be really wrong with your test. Already the input arrays, e.g. 'azimuth' are different. But these are just copied into the output file and should always be the same.

**Comment by daniel-zid** [comment]
There must have been some problems with the different branches. I've checked out the master branch, reset it with --hard HEAD, and this is what I've got. At least the input arrays are good now.

Testing the files 1e18_output.hdf5 and 1e18_output_reference.hdf5 for equality

array multiple_triggers not equal

Arrays are not equal

Mismatch: 10%
 x: array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],...
 y: array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],...

array SNRs of group station_101 not equal

Arrays are not equal

Mismatch: 100%
Max absolute difference: 4.03297484e-09
Max relative difference: 5.03563516e-10
 x: array([26.765744,  4.176577,  5.12592 ,  8.00887 , 25.793275,  8.348002,
        2.244255, 10.030801, 10.458018,  3.493762])
 y: array([26.765744,  4.176577,  5.12592 ,  8.00887 , 25.793275,  8.348002,
        2.244255, 10.030801, 10.458018,  3.493762])

array launch_vectors of group station_101 not equal

Arrays are not equal

Mismatch: 50.6%
Max absolute difference: 1.60770371e-07
Max relative difference: 2.56241992e-07
 x: array([[[[-0.479626,  0.479785,  0.734687],
         [-0.478771,  0.478929,  0.735803]],
...
 y: array([[[[-0.479626,  0.479785,  0.734687],
         [-0.478771,  0.478929,  0.735803]],
...

array maximum_amplitudes of group station_101 not equal

Arrays are not equal

Mismatch: 100%
Max absolute difference: 0.00417697
Max relative difference: 135.06752538
 x: array([[3.182526e-03, 3.230322e-03, 2.941338e-03, 2.926303e-03,
        2.178900e-04, 2.141052e-04, 1.931431e-04, 2.496268e-04],
       [7.833659e-04, 7.888538e-04, 7.361765e-04, 6.126432e-04,...
 y: array([[8.160554e-05, 6.796814e-05, 7.088822e-05, 7.655756e-05,
        2.178900e-04, 2.141058e-04, 1.931431e-04, 2.496268e-04],
       [5.411802e-05, 5.797517e-06, 5.429174e-05, 5.944374e-06,...

array maximum_amplitudes_envelope of group station_101 not equal

Arrays are not equal

Mismatch: 100%
Max absolute difference: 0.00423376
Max relative difference: 149.89038711
 x: array([[3.251301e-03, 3.307151e-03, 3.171449e-03, 3.155489e-03,
        2.859568e-04, 2.732705e-04, 2.835147e-04, 2.946413e-04],
       [9.238391e-04, 9.274047e-04, 8.920465e-04, 8.679419e-04,...
 y: array([[8.178126e-05, 7.472673e-05, 7.180732e-05, 7.830200e-05,
        2.859568e-04, 2.732714e-04, 2.835147e-04, 2.946413e-04],
       [6.015839e-05, 6.146214e-06, 6.007043e-05, 5.949502e-06,...

array multiple_triggers of group station_101 not equal

Arrays are not equal

Mismatch: 10%
 x: array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],...
 y: array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],...

array polarization of group station_101 not equal

Arrays are not equal

Mismatch: 79.2%
Max absolute difference: 2.90879723e-07
Max relative difference: 8.5482588e-07
 x: array([[[[-0.322874,  0.31982 , -0.890768],
         [ 0.321908, -0.325172, -0.889179]],
...
 y: array([[[[-0.322874,  0.31982 , -0.890768],
         [ 0.321908, -0.325172, -0.889179]],
...

array ray_tracing_C0 of group station_101 not equal

Arrays are not equal

Mismatch: 46.2%
Max absolute difference: 2.12081519e-07
Max relative difference: 2.56242057e-07
 x: array([[[0.828114, 0.829595],
        [0.828111, 0.829591],
        [0.829711, 0.831193],...
 y: array([[[0.828114, 0.829595],
        [0.828111, 0.829591],
        [0.829711, 0.831193],...

array ray_tracing_C1 of group station_101 not equal

Arrays are not equal

Mismatch: 41.2%
Max absolute difference: 0.00056852
Max relative difference: 2.78145086e-07
 x: array([[[2042.737978, 2038.794593],
        [2042.746805, 2038.803357],
        [2038.485283, 2034.571914],...
 y: array([[[2042.737978, 2038.794593],
        [2042.746805, 2038.803357],
        [2038.485283, 2034.571914],...

array receive_vectors of group station_101 not equal

Arrays are not equal

Mismatch: 50.8%
Max absolute difference: 4.10512412e-07
Max relative difference: 8.54806262e-07
 x: array([[[[ 0.629766, -0.629974, -0.454454],
         [ 0.628642, -0.62885 ,  0.457556]],
...
 y: array([[[[ 0.629766, -0.629974, -0.454454],
         [ 0.628642, -0.62885 ,  0.457556]],
...

array travel_distances of group station_101 not equal

Arrays are not equal

Mismatch: 41.9%
Max absolute difference: 0.00039053
Max relative difference: 2.44533345e-07
 x: array([[[1604.735324, 1606.386016],
        [1604.741503, 1606.392197],
        [1601.764299, 1603.413916],...
 y: array([[[1604.735324, 1606.386016],
        [1604.741503, 1606.392197],
        [1601.764299, 1603.413916],...

array travel_times of group station_101 not equal

Arrays are not equal

Mismatch: 38.1%
Max absolute difference: 0.00224814
Max relative difference: 2.41240884e-07
 x: array([[[ 9353.236638,  9357.32003 ],
        [ 9353.272062,  9357.355393],
        [ 9336.200853,  9340.314141],...
 y: array([[[ 9353.236638,  9357.32003 ],
        [ 9353.272062,  9357.355392],
        [ 9336.200852,  9340.314141],...

**Comment by cg-laser** [comment]
something must be wrong @daniel-zid , can it be that the antenna pattern was not downloaded? The ray tracing agreement is ok, but your amplitudes differ by orders of magnitude.

**Comment by cg-laser** [comment]
merging with adjusted threholds for now to have a continuous testing

**Comment by cg-laser** [comment]
let's continue discussing this issue here: https://github.com/nu-radio/NuRadioMC/pull/112

**Pull request merged**
