### PR TITLE
Adding script to make multimessenger figure from RNO-G Concept Paper.

### PR DESCRIPTION
**Pull request by anelles**
For documentation purposes and for everyone to have access: the multi-messenger figure. 
Disclaimer: I am sure that the linter will not like the current version.

### CODE REVIEW

**Comment by anelles** [comment]
It is not quite #89 (sorry, @cg-laser this ship may have sailed), but at least I updated this so that everyone has access to the newer figures ...

**Review by shallmann — APPROVED** [review]
Thanks for adding those. I think it would be great to have the sensitivity/flux tables merged to develop.
I trust you that the posted json/txt file numbers are correct ;).
Two minor items which could be modified:
1/ do we need special characters in the file names, like + and =?
2/ maybe it is helpful to add DOI/arXiv references for the tabulated flux values if you still have it?

**Comment by anelles** [comment]
I assume we can still merge this? Or will this now break all the work that @lpyras is doing?

**Comment by lpyras** [comment]
we can merge this :)

**Pull request merged**
