### PR TITLE
Draft: Improve layout of the HDF5 documentation. 

### PR DESCRIPTION
**Pull request by fschlueter**
Changed wrongly labeled shapes for several items. Extended description following the recently discussed changes.

The documentation already includes "changes" which are not yet in the code. I will do so soon. Please let me know if you have any problem with the description etc. 

I changed the shape `n_events` -> `n_showers` for all items on "shower level" please verify. Also, I did not check the "station level" items. Whether their shapes or description are correct. Maybe someone with more experience with those can do so. 

I change from an alphabetic order to one which "groups" certain items together, do you disagree with that?

### CODE REVIEW

**Comment by sjoerd-bouma** [comment]
Thanks Felix! Yes, I originally put in my guess for some of the shapes, only later realizing I was looking at an hdf5 file with only hadronic events in... looks a lot better now.

My only comment would be that right now, all entries in the tables render on a single line, such that there's a lot of horizontal scrolling required unless you're on a 4k screen. If that's fixable, that would be nice.

**Review by sjoerd-bouma — DISMISSED** [review]
I enabled word wrap in tables, which should additionally affect the tables of methods in the documentation of classes.

As far as I'm concerned, having documentation that's running slightly ahead of the code base is no worse than having it lag behind, or be incorrect/incomplete, so feel free to merge this whenever.

**Comment by fschlueter** [comment]
@lpyras, In the process of committing these changes I had a merge conflict. I hope I resolved everything correctly but I would be great if you could check (for 5 min) if your recent changes are still included. Also you have a lot of experiences with the "station-level" items, are the given shapes correct?

**Comment by fschlueter** [comment]
Is there a specific reason to rename `n_showers` to `m_showers`?

**Comment by fschlueter** [comment]
Hey guys, do you think that is meaning full to archive the older version of this documentation. That being said, once we changed the hdf5 files we should bump the version

**Comment by lpyras** [comment]
> Is there a specific reason to rename `n_showers` to `m_showers`?

The number of showers and events on station level is different to the one on global level. I thought I make this visible with using m instead of n. But if you think that’s unnecessary I am happy to change it back :)

**Comment by fschlueter** [comment]
> > Is there a specific reason to rename `n_showers` to `m_showers`?
> 
> The number of showers and events on station level is different to the one on global level. I thought I make this visible with using m instead of n. But if you think that’s unnecessary I am happy to change it back :)

Oh I was not aware of this. Than I think it is very sensible to do so!

**Comment by fschlueter** [comment]
@sjoerd-bouma, do you need to / can you renew your approval?

**Comment by sjoerd-bouma** [comment]
The tests say your cross-reference doesn't work, can you fix that first @fschlueter ? Might just be that you have to remove the `.rst` ending.

**Comment by fschlueter** [comment]
can this be merged?

**Comment by sjoerd-bouma** [comment]
Two minor changes - added the `:orphan:` tag to the old HDF5 structure description. Having rst files not listed in any table of contents (toctree) raises an error, which I think is useful to keep. We could alternatively consider adding a table of contents that lists all previous versions of the HDF5 documentation. I also corrected the path to the image in the old version.

**Review by sjoerd-bouma — APPROVED** [review]
Thanks both!

**Comment by lpyras** [comment]
> can this be merged?

Yes! ☺️

**Pull request merged**
