### PR TITLE
Refactoring some code to obey coding style and increase readability

### PR DESCRIPTION
**Pull request by fschlueter**
Hi folks,
while reading through the modules in order to understand them I did some refactoring: mostly adding whitespaces which help me reading and understanding the code. Should I continue this and should this be merged or is that undesired? 
Cheers

### CODE REVIEW

**Comment by anelles** [comment]
Felix, I think this is great. Please continue to refactor. I think we have done this only very sporadically and there is clearly room to improve.

**Comment by fschlueter** [comment]
Hey, I have locally rebased this branch to develop. Can I make a force push or are you strictly against it? @shallmann @sjoerd-bouma

**Comment by fschlueter** [comment]
Puh this PR is/was terrible outdated and I am not sure that I made everything correct with my rebasing. @lpyras should we abandon it? Sorry for the effort :S

**Comment by fschlueter** [comment]
@lpyras I will close this PR. Feel free to reopen it. Sorry for this!

**Comment by lpyras** [comment]
> @lpyras I will close this PR. Feel free to reopen it. Sorry for this!

Nah, that's fine :)

**Pull request closed without merging**
