### PR TITLE
Tau branching

### PR DESCRIPTION
**Pull request by daniel-zid**
Features:

-Tabulation of tau decay length and energies
-Sorting of double bang events in increasing event index. The numpy insert method was too slow, so I changed the approach using standard python lists.
-Tau branching is included. Tau can decay to the electron channel, muon channel (no shower so far) and hadronic channel. Tau energy is saved, and the shower energy is retrieved during the simulation using the inelasticity distributions (y*E_tau).

### CODE REVIEW

**Comment by anelles** [comment]
@daniel-zid this has been open for too long. It is generating conflicts. 
Is this ready for review?

**Comment by daniel-zid** [comment]
Hi Anna.

Sorry, I did not bring my laptop. The branch has been ready for a while and
it worked fine on my machine. What kind of problems are you having?

O 10:58, ven., 3/05/2019, Anna Nelles <notifications@github.com> escribiu:

**Comment by anelles** [comment]
No urgency, this has time until you are back. I was just going through old pull requests, whether they needed attention and alert people to dormant issues. 

I think it is now in conflict with @cg-laser commits with the looping over stations. Otherwise, I think it is fine.

**Comment by cg-laser** [comment]
I also resolved the conflicts

**Comment by daniel-zid** [comment]
Hi Christian,

You're right. I'll look into it next week.

Schönes Wochenende!

**Comment by daniel-zid** [comment]
Ok, maybe it's better to merge right now so that the branch does not get
left
behind. I'm merging right now. I'll tackle the fiducial problem as soon as
I can.
Keep in mind that at high energies, the tau decay length can be enormous,
so it can be normal that the probability of a double bang is negligible.
That
is precisely what we wanted to know with the code.

**Pull request merged**
