### PR TITLE
add useful function to event: has_triggered

### PR DESCRIPTION
**Pull request by fschlueter**
Is that useful?

### CODE REVIEW

**Comment by anelles** [comment]
This is intended as if any of the triggers has fired, right?
I also think this probably goes on the pile: doesn't harm. However, in the current state it also may be risky, if people don't think about the trigger type anymore.

**Comment by sjoerd-bouma** [comment]
The functionality to return whether 'any' trigger has triggered is not very useful currently, as I don't think there is a way to record events that do not trigger in simulation.py. But I can see how checking for specific triggers would be a useful shortcut from time to time.

**Comment by shallmann** [comment]
@sjoerd-bouma I agree, checking for specific triggers can be handy. Also, I think if the `write_all` will work as expected (another discussion started again by Felix) that might become relevant at some point as well

**Comment by fschlueter** [comment]
@sjoerd-bouma with PR #439 also non-triggered events can be stored if configured.

**Review by cg-laser — APPROVED** [review]
useful function, thanks for adding. 
BTW: You can just pass a trigger name to the function to check for individual triggers. 

A possible improvement could be to allow passing a list of trigger names and then the function calculates the OR of all specified triggers. But this can also be implemented later if anyone needs it.

**Pull request merged**
