### PR TITLE
Update detector description

### PR DESCRIPTION
**Pull request by philippwindischhofer**
According to deployment notes, Station 21 surface pulser was deployed into an empty hole.

The surface pulser location for Station 22 currently also seems to be incorrect and will be corrected in an upcoming update.

Tagging @christophwelling

### CODE REVIEW

**Comment by philippwindischhofer** [comment]
Surface pulser position for Station 22 is now corrected.

**Comment by fschlueter** [comment]
@christophwelling

**Review by anelles — APPROVED** [review]
I am assuming that @philippwindischhofer did not make up numbers, I this should be good to go, even if @christophwelling refuses to review ;)

**Comment by philippwindischhofer** [comment]
Thanks Anna!

**Pull request merged**
