### PR TITLE
Update ara detector

### PR DESCRIPTION
**Pull request by pgiri4**
In existing ARA Json file, the coordinates were printed mistakenly wrong. Ilya, Uzair and I come with necessary update and a file  " PrintJsonFile.C" to Print this detector description. This file calculates the ARA channel coordinates by rotating Station-Centric system to Global-System by an angle of 126.773 (90+ 36.773) degrees i.e. from the direction of ice-flow. The tradional bicone and fourslot antennas are replaced by XFDTD antennas ( Simulated by Chiba group and already available inside NuRadioMC ). A README.md file contains few information on new changes..

[rot1.pdf](https://github.com/nu-radio/NuRadioMC/files/9509026/rot1.pdf)

### CODE REVIEW

**Review by cg-laser — APPROVED** [review]
as far as I can tell it looks good and it unrelated to other parts of NuRadioReco/MC. Thumbs up from me.

**Comment by pgiri4** [comment]
Hi Christian, a brief change in README file has been done. Now, its okay to be merged once you approve this.

**Review by anelles — APPROVED** [review]

**Comment by anelles** [comment]
I agree with Christian, we trust you here on a correct description of ARA. Code looks good. Thanks!

**Comment by pgiri4** [comment]
Thanks, Anna.

**Pull request merged**
