### PR TITLE
Vertex times3

### PR DESCRIPTION
**Pull request by cg-laser**
starting over #172 with starting at commit b03181a90928861b7ba7206a7ed6ede349c5c434

### CODE REVIEW

**Comment by cg-laser** [comment]
this was the last commit before reference files were changed

**Comment by cg-laser** [comment]
but there were still a few commits from #172 that are needed (but not change the reference files).

**Comment by daniel-zid** [comment]
Alright, NuRadioMC works perfectly now. We need to take a look at what NuRadioReco is doing.

**Comment by cg-laser** [comment]
Great! At least we pinpointed down the problem, although I still don't know what makes it fail in NuRadioReco

I think the changes from https://github.com/nu-radio/NuRadioMC/pull/172/commits/eaeb05099c6481d6e5db2f814fa3591759a940cc and https://github.com/nu-radio/NuRadioMC/pull/172/commits/cddaa52d351212ca2b2b6318e07523359f40bde0 are still missing.

**Comment by cg-laser** [comment]
I think this is good for merging now?

**Pull request merged**
