### PR TITLE
also test writing *.nur files

### PR DESCRIPTION
**Pull request by cg-laser**

### CODE REVIEW

**Comment by cg-laser** [comment]
yes maybe, although it might be difficult because newer versions might add more output parameters. So a simple 1to1 comparison will not be sufficient.

**Comment by anelles** [comment]
How about we only compare the trace. That one should be identical and is likely to reveal changes that are not caught in the hdf5 files.

**Comment by cg-laser** [comment]
sounds good

Am 05.09.19 um 11:45 schrieb Anna Nelles:

**Comment by anelles** [comment]
I know why we never tested the .nur files. The file that is generated is 130 MB. @cg-laser this cannot be, right? It is 10 events ...

**Comment by anelles** [comment]
In any case, I have the test ready, if you want to figure out whether we can generate a smaller file sizes ....

**Comment by cg-laser** [comment]
can you try resampling the simulated efield to the detector sampling rate?

Am 06.09.19 um 11:38 schrieb Anna Nelles:

**Comment by anelles** [comment]
It is downsampled by default. That is why the filesize confuses me.

**Comment by cg-laser** [comment]
yes that's weird, we could add debug output to the serialization functions that output how much space what object occupies.

**Comment by anelles** [comment]
I have now stopped the script from writing efields. This makes the file size handlable for now. 
Still 250 KB per event is big. Just assume 0.1Hz trigger of 100 stations. This is 0.8 Mio events in a day -- so a lot of MB.

**Comment by anelles** [comment]
It is very interesting that the traces are not equal across the built-bot and my computer. Will be followed up.

**Comment by anelles** [comment]
Ok, I will merge then like this and we can still reiterate on the non-deterministic results.

**Pull request merged**
