### PR TITLE
Bugfix  cpp path length

### PR DESCRIPTION
**Pull request by clark2668**
This addresses a bug in the CPP based path length finder where it will fail for some integrals. This is addressed by adaptively increasing the size of the allowed relative error within some bound.

I also include a study of the speed of the CPP speed of the ray tracer in the `SignalProp/tests` directory.

### CODE REVIEW

**Comment by cg-laser** [comment]
why did you put a copy (I guess) of the cpp file into the T04 directory? Can't we directly use the original file? I think we should try to avoid code replication.

**Comment by clark2668** [comment]
Yeah, we could, and I agree it would be better to avoid code duplication. I was being lazy. Let me see if I can do something more intelligent...

**Comment by anelles** [comment]
Just a little ping: @clark2668 have you been able to find a solution to this?

**Comment by clark2668** [comment]
Hey @anelles, no, I haven't found time to address this. I might revise the commit stripping out the speed test just to get the bugfix implemented.

**Comment by anelles** [comment]
Great @clark2668. I am just checking all pull-requests periodically to not have them go out of sync for too long. 
I would indeed prioritize the bug fix, if you don't have time to work on more elegant code.

**Comment by clark2668** [comment]
Thanks @anelles for doing that! I think these mods are isolated enough to hopefully not cause major problems. 

And, I think this is ready to go now. I removed the speed test code for now.

**Comment by clark2668** [comment]
@cg-laser--done! :)

**Comment by cg-laser** [comment]
looks good to me. I didn't test it but I assume that you tested that it compiles and works.

**Comment by clark2668** [comment]
The change to the path length integral was tested pretty thoroughly back when I made the bugfix. I didn't test the NAN very aggressively (it compiles and runs, etc), but I'm assuming that change is minor enough to not cause problems. I can exercise it more thoroughly if you think that's important though.

**Comment by cg-laser** [comment]
I think it is fine. Thanks a lot Brian for fixing this!

**Pull request merged**
