### PR TITLE
Save all nur

### PR DESCRIPTION
**Pull request by daniel-zid**
Now the user can make save_all_nur: True/False in the config file to specify whether they want to save all the events on the nur file.

### CODE REVIEW

**Comment by anelles** [comment]
@cg-laser in all your merging efforts. We should merge this too, no?

**Comment by anelles** [comment]
@christophwelling and @cg-laser  I just discussed with Daniel that there is the worry that this doesn't work, because we will create lots of empty .nur files, if there is no trigger. Do you have an example handy with which you could test this?

**Comment by christophwelling** [comment]
That's not a problem. The eventWriter only creates a new file the first time it saves an event. So if you never give it one, it will do nothing. I tested it by setting the trigger threshold in the Veff example ridiculously high and no .nur file was created.

**Comment by anelles** [comment]
Excellent, then I will just  merge this, as it makes sense and does not cause any issues.

**Pull request merged**
